# Materials and Methods

## Data

We used historical deforestation maps for Madagascar at 30m resolution for three time-periods: 1990--2000, 2000--2010, and 2010--2017 [@Vieilledent2018]. We tried to model the observed spatial deforestation process on the period 2000--2010 at the national level. Period 1990--2000 was used to compute the distance to past deforestation for each forest pixel in 2000. Period 2010--2017 was used to compare model forecasts with deforestation observations.

To explain the observed spatial deforestation on the period 2000--2010, we considered various spatial explanatory variables describing: topography (altitude and slope), accessibility (distances to nearest road, town and river), forest landscape (distance to forest edge), deforestation history (distance to past deforestation) and land-tenure variables (protected area system). Characteristics of each variables are summarized in Tab. \@ref(tab:variables).

Altitude (in m) and slope (in degree) at 90 m resolution were obtained from the SRTM Digital Elevation Database v4.1 (<http://srtm.csi.cgiar.org/>). Distances (in m) to nearest road, town and river at 150 m resolution were derived from the OpenStreetMap (OSM) project for Madagascar (<http://www.geofabrik.de/>). To obtain the road network in Madagascar, we considered the "motorway", "trunk", "primary", "secondary" and "tertiary" categories for the "highway" key in OSM. To obtain the network of populated places in Madagascar (that we simply call "towns" in the present study), we considered the "city", "town" and "village" categories for the "place" key in OSM. To obtain the river network in Madagascar, we considered the "river" and "canal" categories for the "waterway" key in OSM. For a more detailed description of each category, see the OSM wiki page (<https://wiki.openstreetmap.org/wiki/Tags>). Distance to forest edge was computed at 30 m resolution from the forest cover map in 2000. Distance to past deforestation was computed at 3 0m resolution from the 1990--2000 forest cover change map. For the protected area system, we used the 20/12/2010 version of the SAPM "Système des Aires Protégées à Madagascar" (<http://rebioma.net/>) and considered both Protected Areas (created before 2003) and New Protected Areas in the SAPM terminology. Polygons representing protected areas were rasterized at 30 m resolution. In total, we obtained 8 spatial explanatory variables to model deforestation location.

## Models

We compared two deforestation models. The first model described in Eq. \@ref(eq:glm) is a simple logistic regression model, a special case of generalized linear model (GLM) for binary data. This model is denoted "glm" in subsequent sections and results. We considered the random variable $y_i$ which takes value 1 if the forest pixel $i$ is deforested on the period 2000--2010 and 0 if it is not. We assumed that $y_i$ follows a Bernoulli distribution of parameter $\theta_i$. In our model, $\theta_i$ represents the spatial probability of deforestation for pixel $i$. We assumed that $\theta_i$ is linked, through a logit function, to a linear combination of the explanatory variables $X_i \beta$, where $X_i$ is the vector of explanatory variables for pixel $i$ and $\beta$ is the vector of model parameters to be estimated.

\begin{equation}
\begin{split}
  y_i \sim \mathcal{B}ernoulli(\theta_i)\\
  \text{logit}(\theta_i) = X_i \beta
\end{split}
(\#eq:glm)
\end{equation}

The second model described in Eq. \@ref(eq:icar) includes additional random effects $\rho_j$ for each spatial cell $j$ of a 10 $\times$ 10 km grid covering Madagascar. This grid resolution was choosen in order to have a reasonable balance between a good representation of the spatial variability of the deforestation process and the number of parameters. We assumed that random effects were spatially autocorrelated through an intrinsic conditional autoregressive (iCAR) model [@Besag1991;@Banerjee2014]. This model is denoted "icar" in subsequent sections and results. In a iCAR model, the random effect $\rho_j$ associated to cell $j$ depends on the values of the random effects $\rho_{j^{\prime}}$ associated to neighbouring cells $j^{\prime}$. In our case, the neighbouring cells are cells connected to the target cell $j$ through a common border or corner (cells defined by the "king move" in chess). The number of neighbouring cells for cell $j$, which might vary, is denoted $n_j$. 

\begin{equation}
\begin{split}
  y_i \sim \mathcal{B}ernoulli(\theta_i)\\
  \text{logit}(\theta_i) = X_i \beta + \rho_j\\
  \rho_j \sim \mathcal{N}ormal(\sum_{j^{\prime}} \rho_{j^{\prime}} / n_j,V_{\rho} / n_j)
\end{split}
(\#eq:icar)
\end{equation}

The first model can be viewed as a "process-based" model for which variables are selected on an _a priori_ knowledge of the deforestation process. For example, we assumed that the risk of deforestation decreases with the distance to road and forest edge, and is lower in protected areas. The second model can be viewed as a model combining a "process-based" part and a "pattern-oriented" part. Additional spatial random effects $\rho_j$ account for unmeasured or unmeasurable variables [@Clark2005] that explain a part of the residual spatial variation in the deforestation process (the residual spatial "pattern") that is not explained by the fixed environmental variables ($X_i$). While the first model has only 9 parameters to be estimated (one intercept parameter plus 8 slope parameters for the explanatory variables), the second model has 6,266 parameters to be estimated, including the 6,257 spatial random effects for the 10 $\times$ 10 km cells covering whole Madagascar (for which lands cover 587 000 km$^2$).

We used a random sample of 20,000 forest pixels in 2000 to fit the two models. The sample was stratified between 10,000 deforested pixels in 2000--2010 and 10,000 non-deforested pixels. A balanced sample between deforested and non-deforested pixels is preferable in our case [@Dezecache2017]. First, deforestation events are rare (~1 %/yr) and a non-stratified sample would lead to very few observations of deforestation events, rendering difficult a good estimation of the slope parameters for the explanatory variables. Second, only the value of the linear model intercept is affected by this balanced sampling, which is not the case for the slope or random parameters. In our case, a biased estimate of the intercept is not an issue, as we are not interested in estimating the intensity of deforestation but the relative probability of deforestation between pixels. Function `sample()` from the `forestatrisk` Python package was used for fast stratified sampling and for extracting variable values at each point.

Parameter inference was done in a hierarchical Bayesian framework. Non-informative priors were used for all parameters: $\beta \sim \mathcal{N}ormal(\text{mean}=0,\text{var}=10^6)$ and $V_{\rho} \sim 1/\mathcal{G}amma(\text{shape}=0.05,\text{rate}=0.0005)$. We run a Markov Chain Monte Carlo (MCMC) of 7000 iterations. We discarded the first 2000 iterations (burn-in phase) and we thinned the chain each 5 iterations (to reduce autocorrelation between samples). We obtained 1000 estimates for each parameter. MCMC convergence was visually checked looking at MCMC traces and parameter posterior distributions. Function `model_binomial_iCAR()` from the `forestatrisk` Python package was used for parameter inference. This function calls an adaptive Metropolis-within-Gibbs algorithm [@Rosenthal2011] written in C for maximum computation speed. 

## Model comparison and validation

### Model comparison using percentage of deviance explained and cross-validation

We computed the deviance $\mathcal{D}$ of the two models with the formula $\mathcal{D}=-2 \log \mathcal{L}$, $\mathcal{L}$ being the likelihood of the model, i.e. the probability of observing the data given the model and estimated parameters. We compared the deviance of the two models with the deviances of both the "null" model and the "full" model. The "null" model assumes a constant probability of deforestation for all theobservations and has only one parameter, the intercept of the linear relationship. At the other extreme, the "full" model has as many parameters as there are observations. We then computed the percentage of deviance explained by each model, considering that the "null" model explains 0% of the deviance and the "full" model explains 100% of the deviance.

We also performed a cross-validation to compare models using an independent validation data-set of 20,000 forest pixels in 2000. Again, the sample was stratified between 10,000 deforested pixels in 2000--2010 and 10,000 non-deforested pixels. We used the fitted models to predict the deforestation probability of all the pixels of the validation data-set. To transform the deforestation probabilities into binary values, we identified the probability threshold respecting the percentage of deforested pixels (eg. the mode of the probabilities for a deforestation rate of 50%). Using model predictions and observations, we computed several accuracy indices: the Area Under the ROC Curve (AUC), the Figure of Merit (FOM), the Overall Accuracy (OA), the Expected Accuracy (EA), the Kappa of Cohen (K), the Specificity (Spe), the Sensitivity(Sen), and the True Skill Statistics (TSS). A detailed description of these indices can be found in @Pontius2008 (for the FOM) and @Liu2011 (for all the other indices). Formulas used to compute these indices are presented in Appendix 1.

Because the value of these indices depends on the deforestation rate [@Pontius2008], we computed the accuracy indices for various percentage of deforested pixels: 1, 5, 10, 25 and 50%. To do so, we selected subsamples of the deforested pixels in our validation data-set at random.

### Comparing model forecasting skills

#### Computing the spatial probability of deforestation in 2010

We used the fitted models to predict the deforestation probability of all the forest pixels for the year 2010. Distances to forest edge in 2010 and to past deforestation in 2000--2010 were recomputed from forest cover maps in 2000 and 2010. All other explanatory variables were supposed constant. Spatial random effects were also supposed constant through time.

For the "icar" model, before computing the predictions of the deforestation probability, the spatial random effects at 10 km were interpolated at 1 km using a bicubic interpolation method. This was done in order to obtain spatial random effects at a resolution closer to the original forest raster resolution of 30 m, and to smooth the deforestation probability spatially. 

Deforestation probabilities (float values in the interval $[0, 1]$) were transformed as integer values on the interval $[\![1, 65535]\!]$. This allowed us to record the large raster of probabilities as UInt16 type and save space on disk. We then obtained a map of the relative probability of deforestation for the year 2010 at 30 m resolution.

In 2010, Madagascar was covered by 9.3 Mha of natural forest corresponding to more than 104 M pixels at 30 m resolution. Predictions were computed using functions `predict_raster*()` from the `forestatrisk` Python package which make computation fast and efficient (with low memory usage) by treating raster data by blocks.

#### Forecasting forest cover change on the period 2010--2017

We computed the observed deforestation $D$ (in ha) on the period 2010--2017 from the forest cover maps at these two dates. To forecast the forest cover change in 2010--2017 with our models, we used the previously derived maps of relative probability of deforestation in 2010. The resolution of these maps is $r=30$ m, equivalent to $r_{\text{ha}}=0.09$ ha. We computed a probability threshold $\theta_T$ in the interval $[\![1, 65535]\!]$ identifying the $n$ forest pixels in 2010 with the highest probability of deforestation so that $n r_{\text{ha}} = D + \epsilon$. Because deforestation probabilities have finite values in $[\![1, 65535]\!]$, some forest pixels might have the same deforestation probability and it might not be possible to identify $\theta_T$ such that $\epsilon=0$. We thus selected the threshold $\theta_T$ minimizing $\epsilon$. We obtained negligible $\epsilon$ ($<$ 32,000 ha) compared to $D$ (874,211 ha) for both models. We considered those $n$ forest pixels in 2010 as deforested on the period 2010--2017 and derived the forest cover change map on that period.

#### Model validation on the period 2010--2017

We compared the forest cover change maps obtained from the modelling and forecasting procedure with the observed forest cover change map on the period 2010--2017. Forest cover change maps have a high resolution of 30 m. At high resolution, a pixel-to-pixel comparison provides limited information on the spatial accuracy of the predictions because it ignores neighborhood relationships. To overcome this problem, a multiple resolution accuracy assessment can be performed [@Pontius2004]. Following the methodology proposed by @Pontius2004, we computed two accuracy indices, the Figure of Merit (FOM) and the Overall Accuracy (OA), at multiple resolutions from 30 m to 15 km. In our case, the "quantity disagreement" census @Pontius2004 between observations and predictions, equivalent to our previously estimated $\epsilon$, was assumed negligeable. The accuracy indices we computed allow us to estimate a "location disagreement" census @Pontius2004 between observations and predictions. Confusion matrices and accuracy indices at multiple resolutions were compute with functions `resample_sum()`, `confmat()`, and `accuracy()` from the `forestatrisk` Python package.

### Comparing model outputs for long-term forecasts (2010--2050)

To look at the consequences of using either the "glm" or the "icar" model for long-term forecasts, we forecasted deforestation on the period 2010--2050 using our two models calibrated on the period 2000--2010. Explanatory variables and spatial random effects were supposed constant for this period of time. We considered an "average" scenario assuming that annual deforestation on the period 2010--2050 would roughly be the same as the observed mean annual deforestion on the period 2000--2017 (84 Kha/yr, @Vieilledent2018data). Based on this "average" scenario, 3.4 Mha of natural forest should be deforested on the 40-year period 2010--2050. This would correspond to a future forest cover of 6.0 Mha in 2050.

## Forecasting deforestation in Madagascar for 2017--2050 and 2050--2100

We used only the "icar" model.

Model parameters were re-estimated using data on the two periods 2000-2010 and 2010-2017. We selected 

The second scenario takes into account the demographic growth in Madagascar, which is close to 3 \%/yr [@Raftery2012; @Vieilledent2013], and the link between population and deforestation. We considered the following model adapted from @Barnes1990: $\log(D_{t,t+1}) = \beta_0 + 0.607 \log(F_t) + 0.493 \log(P_t) + \varepsilon_t$ with $\varepsilon_t \sim \mathcal{N}ormal(0,\sigma^2)$, where $D_{t,t+1}$ is the mean annual deforestation (in ha/yr) between times $t$ and $t+1$, $F_t$ is the forest cover (in thousand hectares) at time $t$, and $P_t$ is the population size (in thousand people) at time $t$. This model was fitted to data from 22 African countries in 1980, but not including Madagascar. We assumed that the relationship between people and deforestation in continental Africa holds true for Madagascar as well, as deforestation is mainly due to small scale family farming in both regions [@Curtis2018]. Using historical deforestation data from @Vieilledent2018data on the interval 2000--2017 (4 different time periods) and population data from the United Nations World Population Prospect [@UN2017], we estimated parameters $\beta_0$ and $\sigma^2$ for Madagascar with a weighted linear regression (weights were equal to period length). We obtained $\beta_0 = -6.088$ and $\sigma^2 = 0.279$. Following @Barnes1990, we used this model to iteratively forecast deforestation and forest cover from 2017 to 2050 using a time step of 3 years for 2017-2020 and 5 years for 2020-2050 (Appendix 2). Based on this demographic scenario, 3.3 Mha should be deforested on the period 2017--2050, and 7.4 Mha on the period 2017--2100. This corresponds to a projected forest cover of 5.2 Mha in 2050 and 1.0 Mha in 2100.

\newpage
