# Supplementary text for Materials and Methods

## Study areas

We defined 119 study areas representing 92 countries (Fig. \@ref(fig:study-areas)) and covering the integrality of the tropical moist forest in the world, at the exception of some islands (eg. Sao Tome and Principe or Wallis-and-Futuna). Each country was identified by one unique three-letter code following the ISO 3166-1 standard (eg. MDG for Madagascar or GUF for French Guiana). Most of the countries corresponded to one unique study area, with three exceptions: Brazil, India, and Australia. Brazil, because of its large size, was divided into 26 study areas corresponding to the 26 administrative states (the state of Goias including the Federal District). For India, which is also a large country, the tropical moist forest is located in three distinct regions far from each other. We thus considered three independent study areas for India: the Western Ghats, North-East India (including the West Bengal), and the union territory of the Andaman and Nicobar Islands. For Australia, we only considered the Queensland state as a study area. Data sampling and spatial deforestation modelling were performed independently for each study area. Study area borders were obtained from version 3.6 of the Global Administrative Areas database (<https://gadm.org>). We used level-0 data for study areas corresponding to countries and level-1 data for study areas corresponding to states or regions. We grouped the study areas in three continents (Fig. \@ref(fig:study-areas)): America (64 study areas for 39 countries), Africa (32 study areas for 32 countries), and Asia (23 study areas for 21 countries).

## Past forest cover change maps

For each study area, we derived past forest cover change maps for two time periods: January 1^st^ 2000 -- January 1^st^ 2010, and January 1^st^ 2010 -- January 1^st^ 2020 from the forest cover change annual product version v1\_2020 by @Vancutsem2021. The annual product by @Vancutsem2021 classifies Landsat image pixels at 30 m resolution in 6 main categories (1: undisturbed, 2: degraded, 3: deforested, 4: regrowth, 5: water, and 6: other land cover) for each year (on the 31^st^ of December) between 1990 and 2020 (31 years of data for v1\_2020), and allows identifying tropical moist forest pixels at each date (Table \@ref(tab:cat-annual-product)). This classification is based on an expert system analyzing time-series data at the pixel level extracted from the full Landsat satellite image archive on the period 1982--2020. For our forest definition, we only considered _natural old-growth tropical moist forests_, disregarding plantations and regrowths. We included degraded forests (not yet deforested) in our forest definition. As a consequence, we considered all pixels falling in categories 1 and 2 in the annual product (Table \@ref(tab:cat-annual-product)), to be natural old-growth tropical moist forest pixels (simply abbreviated "forest" in this manuscript). Because several decades are usually necessary to reach the state of old-growth forest, we assumed every pixel classified as "forest" at a given date between 2000 and 2020 to be also classified as "forest" in the previous years of that period of time. We thus obtained three forest cover maps for the dates January 1^st^ 2000, January 1^st^ 2010, and January 1^st^ 2020. We combined these three maps to obtain high-resolution forest cover change maps in the periods 2000--2010--2020 at 30 m resolution in the humid tropics (Fig. \@ref(fig:fcc-maps)). We used Google Earth Engine [@Gorelick2017] to process the annual product by @Vancutsem2021 and derive the past forest cover change map for each study area. An interactive forest cover change map for the humid tropics is available at <https://forestatrisk.cirad.fr/maps.html>.

We did not consider potential forest regrowth in our forest definition for three main reasons. First, throughout the humid tropics, forest regeneration involves much smaller areas than deforestation [@Hansen2013; @Vancutsem2021]. Second, there is little evidence of natural forest regeneration in the long term in the tropics [@Grouzis2001]. This can be explained by several ecological processes following deforestation such as soil erosion [@Grinand2017], and reduced seed bank due to fire-induced deforestation and soil loss [@Grouzis2001]. Moreover, in areas where forest regeneration is ecologically possible, young forest regrowths are more easily re-burnt for agriculture and pasture [@Vieilledent2020]. Third, young secondary forests generally provide more limited ecosystem services compared to old-growth natural forests in terms of biodiversity [@Gibson2011] and carbon storage [@Blanc2009].

## Spatial explanatory variables

To explain the observed deforestation during the period 2010--2020, we considered a set of spatial explanatory variables (Fig. \@ref(fig:var)) describing: topography (altitude and slope), accessibility (distances to nearest road, town, and river), forest landscape (distance to forest edge), deforestation history (distance to past deforestation), and land conservation status (presence of a protected area). This set of variables were selected based on an _a priori_ knowledge of the deforestation process [@Geist2002; @Vieilledent2013; @Brown1994]. For example, the risk of deforestation is supposed to decrease with the distance to road and forest edge (lower accessibility), to increase at lower elevation and slope (higher probability to find arable lands), and to decrease in protected areas (higher level of protection).

Elevation (in m) and slope (in degree) at 90 m resolution were obtained from the SRTM Digital Elevation Database version v4.1 (<http://srtm.csi.cgiar.org/>). Distances (in m) to nearest road, town and river at 150 m resolution were computed from the road, town and river networks which were obtained from the OpenStreetMap (OSM) project (<https://www.openstreetmap.org/>). OSM country data were downloaded from two websites: Geofabric (<http://download.geofabrik.de/>) and OpenStreetMap.fr (<https://download.openstreetmap.fr/extracts/>) depending on the availability of the data for each country. To obtain the road network in each country (Fig. \@ref(fig:data-roads)), we considered the "motorway", "trunk", "primary", "secondary" and "tertiary" categories for the "highway" key in OSM. Our dataset included a total of 3,606,841 roads. To obtain the network of populated places in each country (that we simply call "towns" in the present study), we considered the "city", "town" and "village" categories for the "place" key in OSM. To obtain the river network, we considered the "river" and "canal" categories for the "waterway" key in OSM. For a more detailed description of each category, see the OSM wiki page (<https://wiki.openstreetmap.org/wiki/Tags>). OSM data have been downloaded in March 2021 for all countries. Distance to forest edge was computed at 30 m resolution from the forest cover map in 2010. Distance to past deforestation in 2010 was computed at 30 m resolution from the 2000--2010 forest cover change map. To minimize border effect for the computation of distance to forest edge and distance to past deforestation, a buffer of 10 km around each study area extent was considered. Data on protected areas (Fig. \@ref(fig:data-pa)) were obtained from the World Database on Protected Areas (<https://www.protectedplanet.net>, @WDPA2020) using the `pywdpa` Python package (<https://pypi.org/project/pywdpa/>). WDPA data have been downloaded in March 2021 for all countries. For the analyses, we only retained protected areas defined by at least one polygon (we removed all protected areas defined by a point) and which had the following status: "Designated", "Inscribed", "Established", or "Proposed" before January 1^st^ 2010 (we removed all "Proposed" protected areas after that date). Data included protected areas of all IUCN categories (from Ia to VI) and of all types defined at the national level (e.g. National Parks, Reserves), even if the type and IUCN category were not reported. Our dataset included a total of 89,855 protected areas. Polygons representing protected areas were rasterized at 30 m resolution.

In total, we obtained eight spatial explanatory variables to model the spatial probability of deforestation. Characteristics of each explanatory variable are summarized in Table \@ref(tab:variables) and correlation between variables are available in Fig. \@ref(fig:corr-var). Using data at a resolution closest to the resolution of the forest cover change map (30 m) to model deforestation ensures the capture of fine spatial scale deforestation processes. In particular, we demonstrate in this study the preponderant effect of the distance to forest edge which acts at a distance much lower than 1 km on the risk of deforestation.\enlargethispage{\baselineskip}

## Data sampling for spatial modelling of deforestation

With the spatial model of deforestation, our aim was to estimate the effects of a set of variables in determining the location of the deforestation (or "allocation" census @Pontius2011) and compute the relative probability of deforestation for each forest pixel. With the spatial model, our objective was not to estimate the intensity of the deforestation (or "quantity" census @Pontius2011), that could be expressed in %/year or in ha/year for example. A balanced sampling between deforested and non-deforested pixels is preferable in this case [@Vieilledent2013; @Dezecache2017]. Because deforestation events are rare ($\approx$ 1 %/yr), a non-stratified random sampling would lead to very few observations of deforestation events, rendering difficult a good estimation of the effects of the explanatory variables. Stratified balanced sampling provided unbiased estimates of the model's parameters, except for the model's intercept (estimated average deforestation). Having a biased model intercept (which has the same value for all forest pixels) is not a problem as we are interested in estimating a _relative_ probability of deforestation between forest pixels.

As a consequence, we performed a stratified balanced sampling between (i) forest pixels in 2010 which have been deforested on the period 2010--2020 ("deforested" pixels), and (ii) forest pixels in 2010 which have not been deforested on that period of time and which represent the remaining forest in 2020 ("non-deforested" pixels). Forest pixels in each category were sampled randomly (Fig. \@ref(fig:sampling)). To maximize the representativity of the data, the total number of forest pixels sampled in each study area for the year 2010 was chosen proportionally to the area of forest in 2010 in that study area (2000 points for 1 Mha of forest), with the condition that this number had to be between 20,000 (to be representative of the deforestation process) and 100,000 (to limit computation time). When, for a specific study area, the total number of pixels in one of the two categories (deforested vs. non-deforested pixels) was $\leq$ 10,000, all the pixels of that category were included in the sample. This could happen for study areas with low moist forest cover such as small islands (eg. Antigua and Barbuda). For each sampled pixel, we retrieved information regarding the eight computed explanatory variables at their original spatial resolution. When the information was not complete for a given pixel (eg. elevation and slope data missing for a forest pixel located close to the sea border), the observation was removed from the dataset. Missing information affected a minority of pixels. The global dataset included a total of 3,197,942 observations: 1,601,125 non-deforested pixels and 1,587,817 deforested pixels, corresponding to an area of 144,914 ha and 142,908 ha, respectively (Table \@ref(tab:samp-size)).

## Spatial deforestation model

Using observations of forest cover change in the period 2010--2020, we modelled the spatial probability of deforestation as a function of the $n$ explanatory variables using a logistic regression. We considered the random variable $y_i$ which takes value 1 if the forest pixel $i$ was deforested in the period 2010--2020 and 0 if it was not. We assumed that $y_i$ follows a Bernoulli distribution of parameter $\theta_i$ (Eq. \@ref(eq:icar)). In our model, $\theta_i$ represents the spatial relative probability of deforestation for pixel $i$. We assumed that $\theta_i$ is linked, through a logit function, to a linear combination of the explanatory variables $X_i \beta$, where $X_i$ is the vector of explanatory variables for pixel $i$, and $\beta$ is the vector of effects $[\beta_1, \ldots, \beta_n]$ associated with the $n$ variables. All the continuous explanatory variables were normalized before fitting the model. The model includes an intercept $\alpha$. To account for the residual spatial variation in the deforestation process, we included an additional random effect $\rho_{j(i)}$ for each spatial cell $j$ of a 10 $\times$ 10 km grid covering each study area (Fig. \@ref(fig:grid)). This grid resolution was chosen in order to have a reasonable balance between a good representation of the spatial variability of the deforestation process and a limited number of parameters to estimate. A sampled forest pixel $i$ was associated with one cell $j$ and one random effect $\rho_{j(i)}$. We assumed that random effects were spatially autocorrelated through an intrinsic conditional autoregressive (iCAR) model [@Besag1991]. This model is denoted "icar" in subsequent sections and results. In an iCAR model, the random effect $\rho_j$ associated with cell $j$ depends on the values of the random effects $\rho_{j^{\prime}}$ associated with neighbouring cells $j^{\prime}$. In our case, the neighbouring cells are connected to the target cell $j$ through a common border or corner (cells defined by the "king move" in chess, see Fig. \@ref(fig:grid)). The variance of the spatial random effects $\rho_j$ was denoted $V_{\rho}$. The number of neighbouring cells for cell $j$, which might vary, was denoted $n_j$. Spatial random effects $\rho_j$ account for unmeasured or unmeasurable variables [@Clark2005] that explain a part of the residual spatial variation in the deforestation process that is not explained by the fixed spatial explanatory variables ($X_i$).

\begin{equation}
\begin{split}
  y_i \sim \mathcal{B}ernoulli(\theta_i)\\
  \text{logit}(\theta_i) = \alpha + X_i \beta + \rho_{j(i)}\\
  \rho_{j(i)} \sim \mathcal{N}ormal(\sum_{j^{\prime}} \rho_{j^{\prime}} / n_j,V_{\rho} / n_j)
\end{split}
(\#eq:icar)
\end{equation}

## Variable selection

Variable selection was performed using a backward elimination procedure. All the spatial explanatory variables in our dataset should decrease the deforestation risk (having a negative effect on the probability of deforestation). For example, the probability of deforestation should decrease with the distance to the forest edge and should also decrease inside a protected area. Our variable selection procedure was thus not based on statistical significance but on background knowledge regarding the deforestation process and on the interpretability of the variable effects [@Heinze2018]. For each study area, we started to fit a model with the full set of explanatory variables (eight variables). At each step of the procedure, we removed the variables having a positive effect on the probability of deforestation. This was done in order to avoid unrealistic predictions of the spatial probability of deforestation at the scale of the study area. For example, it is not realistic to observe, at the country scale, a decrease of the deforestation with the distance to forest edge (higher deforestation risk in the core of the forest compared with forest edge). This might happen in a particular context for a very specific region but is very unlikely at the country level. In most of the cases, when we found a positive effect for a given explanatory variable, it was non-significant (95% credible interval including zero). On the contrary, when we found a negative but non-significant effect for a given explanatory variable, we kept this variable in the model for the predictions. This effect, albeit non-significant, was interpretable given our background knowledge of the deforestation process and was relatively lower than the effects associated with the other variables.

## Parameter inference

Parameter inference was done in a hierarchical Bayesian framework. We used the function `model_binomial_iCAR()` from the `forestatrisk` Python package [@Vieilledent2021a] for parameter inference. This function calls an adaptive Metropolis-within-Gibbs algorithm written in C for maximum computation speed. Non-informative priors were used for all parameters: $\alpha \sim \mathcal{N}ormal(\text{mean}=0,\text{var}=10^6)$, $\beta \sim \mathcal{N}ormal(\text{mean}=0,\text{var}=10^6)$, and $V_{\rho} \sim 1/\mathcal{G}amma(\text{shape}=0.05,\text{rate}=0.0005)$. During the variable selection procedure, we run a Markov Chain Monte Carlo (MCMC) of 2000 iterations, discarding the first 1000 iterations (burn-in phase). For the final model, we repeated the parameter inference using a longer MCMC of 10,000 iterations. We discarded the first 5000 iterations (burn-in phase), and we thinned the chain each 5 iterations (to reduce autocorrelation between samples). MCMC convergence was visually checked looking at MCMC traces and parameter posterior distributions. We obtained 1000 estimates for each parameter. We used these 1000 estimates to compute the mean and 95% credible interval of each parameter (Tables \@ref(tab:par)--\@ref(tab:road)). We also back-transformed the parameters using the mean and standard-deviation of each continuous variable for each study area. Doing so, we can use Eq. \@ref(eq:icar) to compute the change in the probability of deforestation associated with a particular change in the explanatory variables, in their original units. The value of the intercept $\alpha$ of the model is affected by the back-transformation, but not the effect of protected areas nor the variance of the spatial random effects, which are left unchanged (Tables \@ref(tab:bt-par), \@ref(tab:bt-par-region)).

## Model comparison

### Alternative models

We compared the performance of the "icar" model at predicting deforestation with three other models: a null model (denoted "null"), a simple generalized linear model ("glm"), and a random forest model ("rf"). The "null" model assumes that all the slope parameters have value zero (no effect of explanatory variables), and that all the spatial random effects have also value zero (no residual regional variability in the deforestation process). For the "null" model, the probability of deforestation is only determined by a mean intercept common to every forest pixel ($\text{logit}(\theta_i) = \alpha$). The simple "glm" is a logistic regression which does not include spatial random effects (no residual regional variability in the deforestation process). For the "glm" model, the probability of deforestation is only determined by the mean intercept $\alpha$ and the parameters $\beta$ associated with each explanatory variables ($\text{logit}(\theta_i) = \alpha + X_i \beta$). Using simple "glm" models is a commonly proposed approach for spatial modelling of deforestation [@Mas2007; @Rosa2014; @Ludeke1990; @Soares-Filho2002]. The random forest model [@Breiman2001] is a machine learning approach using an ensemble of random classification trees (where both observations and features are chosen at random to build the classification trees) to predict the deforestation probability for a forest pixel. Random forest has been intensively used for species distribution modelling [@Thuiller2009] and is now also commonly used for spatial modelling of deforestation [@Grinand2020; @Zanella2017]. The "glm" and "rf" models were fitted using functions `LinearRegression` and `RandomForestClassifier` respectively, both available in the `scikit-learn` Python package [@Pedregosa2011]. We used the same set of selected explanatory variables for the "glm" and "rf" models as those used for the final "icar" model. For the "rf" model, we set the number of random classification trees to 500.

### Percentage of deviance explained

We computed the deviance $\mathcal{D}$ of the four models ("icar", "null", "glm", and "rf") with the formula $\mathcal{D}=-2 \log \mathcal{L}$, $\mathcal{L}$ being the likelihood of the model, i.e. the probability of observing the data given the model and estimated parameters. The deviance is a measure of error and a model with a lower deviance fits better the data. We also considered the deviance of the "full" model (also called the saturated model) which has as many parameters as there are observations. When $y_i=0$, the deforestation probability predicted by the full model is 0. When $y_i=1$ the deforestation probability predicted by the full model is 1. The deviance of the full model is then equal to 0. Considering that the "null" model explained 0% of the deviance and the "full" model explains 100% of the deviance, we then computed the percentage of deviance explained by each of the three other models: "icar", "glm", and "rf".

### Cross-validation procedure

To compare the performance of the "icar", "glm", and "rf" models at predicting correctly the relative probability of deforestation on independent observations, we also performed a five-fold cross-validation procedure. We used 70% of the observations for the model training and 30% of the observations for the model validation. We used the fitted models to predict the deforestation probability of all the forest pixels of the validation dataset. To transform the deforestation probabilities into binary values, we identified the probability threshold respecting the percentage of deforested pixels in the validation dataset (e.g., the mode of the predicted probabilities for a percentage of 50% of deforested pixels). Consequently, the predicted number of deforested pixels was equal to the observed number of deforested pixels in the validation dataset. This implies that there was no "quantity disagreement" (_sensu_ @Pontius2011) for any of the three models in the cross-validation procedure. Through this cross-validation, we only compared the ability of the models to correctly identify the pixels to be deforested, given a particular mean deforestation rate. This corresponds to estimating the "allocation disagreement" (_sensu_ @Pontius2011) for each of the three models. Using model predictions and observations in the validation dataset, we computed several accuracy indices: the Area Under the ROC Curve (AUC), the Figure of Merit (FOM), the Overall Accuracy (OA), the Specificity (Spe), the Sensitivity (Sen), and the True Skill Statistics (TSS). A detailed description of these indices can be found in @Pontius2008 (for the FOM) and @Liu2011 (for all the other indices). Formulas used to compute these indices are presented in Tables \@ref(tab:confusion-matrix), \@ref(tab:accuracy-indices).

### Model selection

For all the study areas, we found that the percentage of deviance explained for the "rf" model was much higher than for the "icar" and "glm" models (Table \@ref(tab:accuracy)), suggesting that the "rf" model was fitting much better the data than the two other models. Nevertheless, when looking at the results of the cross-validation procedure, the "rf" model had a lower accuracy in comparison with the "icar" model (Table \@ref(tab:accuracy)). These two results show clearly that the "rf" model was overfitting the data and was less performant at predicting the probability of deforestation at new sites than the "icar" model. This can be explained by the fact that the strong nonlinear relationship between explanatory variables and the spatial probability of deforestation, which is estimated by the "rf" model based on the training dataset, does not represent the true relationship at the landscape scale. This limitation associated with machine-learning techniques such as random forest has already been raised in previous scientific articles dealing with large scale mapping of ecological variables [@Ploton2020]. On the contrary, the "icar" model had the highest accuracy indices of the three models suggesting a better predictive performance than the "glm" and "rf" models. Also, the "icar" model increased the explained deviance from 39.3 to 53.3% in average in comparison with the "glm" model. This shows that environmental explanatory variables alone explain a relative small part of the spatial deforestation process and that including spatial random effects to account for unexplained residual spatial variability strongly improves model fit (+14.0% of deviance explained in average) and model predictive performance (+7.4% for the TSS for example). Same results were obtained when comparing accuracy indices for the three statistical models per continent (Table \@ref(tab:accuracy-cont)). We thus selected the "icar" model for predicting the spatial probability of deforestation for all the study areas.

## Computing the spatial probability of deforestation for the year 2020

Before computing the predictions of the deforestation probability, the spatial random effects at 10 km were interpolated at 1 km using a bicubic interpolation method (Fig. \@ref(fig:rho)). This was done in order to obtain spatial random effects at a resolution closer to the original forest raster resolution of 30 m, and to smooth the deforestation probability predictions spatially.

Distance to forest edge in 2020 was recomputed from the forest cover map in 2020 at 30 m resolution. Distance to past deforestation in 2020 was recomputed from the 2010--2020 forest cover change map at 30 m resolution. All other explanatory variables (protected areas, distance to nearest road, town and river, elevation, and slope) were supposed unchanged between years 2010 and 2020. Using rasters of explanatory variables at their original resolution, interpolated spatial random effects at 1 km resolution, and the fitted "icar" model for each study area, we computed the spatial probability of deforestation at 30 m resolution for the year 2020 for each study area.

Deforestation probabilities (float values in the interval $[0, 1]$) were rescaled and transformed to integer values in the interval $[\![1, 65535]\!]$. This allowed us to record the large rasters of probabilities as UInt16 type (using zero as no-data value) and save space on disk. We then obtained a map of the relative probability of deforestation for the year 2020 at 30 m resolution (Fig. \@ref(fig:sm-prob)). An interactive global map of the spatial probability of deforestation is available at <https://forestatrisk.cirad.fr/maps.html>.

## Forecasting forest cover change for the period 2020--2110

For each study area, we computed the observed mean annual deforested area $d$ (in ha/yr) on the recent ten-year period 2010--2020 (from January 1^st^ to January 1^st^) using the forest cover change annual product by @Vancutsem2021 (Tables \@ref(tab:fcc-hist), \@ref(tab:fcc-hist-reg)). The year 2020 was not considered to compute the recent mean annual deforested area as more disturbance events need to be observed on Landsat satellite images to disentangle degradation from deforestation for that year. As a consequence, most disturbance events are classified as degradation, and deforestation is underestimated for that specific year.

To forecast the forest cover change at a particular date $y$ in the future, we computed the estimated total deforestation $D_y$ (in ha) between years 2020 and $y$ assuming a "business-as-usual" scenario. The business-as-usual scenario makes the assumption of an absence of change in the deforestation intensity in the future (no increase in the deforestation intensity that could be attributable to a future increase in the demand of agricultural commodities for example, nor decrease in the deforestation intensity that could be attributable to new conservation policies or increase in agricultural yields for example). The business-as-usual scenario also makes the assumption that the spatial deforestation process will remain the same in the future (assuming a constant effect of the spatial explanatory variables in the future) and that areas with a higher relative probability of deforestation will remain the same in the future. To compute the total deforestation $D_y$ (in ha) between years 2020 and $y$, we projected the mean annual deforestation $d$ on the time interval $y-2020$: $D_y=d \times (y-2020)$.

For Brazil, which was divided into 26 study areas, the mean annual deforested area $d$ was supposed constant at the country level, not at the study area level. Indeed, we assumed that deforestation inside Brazil should spread between states and should not stop at the state administrative borders. As a consequence, when all the forest of a specific state in Brazil was deforested, the corresponding residual deforested area for that state was redistributed to the other states of Brazil still having forest. This ensured that the annual deforested area was constant for Brazil, but imply an increase of the annual deforested area with time for some states. We assumed that this contagious deforestation between study areas was only valuable for connected study areas inside a specific country (here, Brazil). On the contrary, we assumed that it was much less likely to observe contagious deforestation between two neighbouring countries. First, because of the presence of less permeable international borders, and second, because the socio-economic factors driving the intensity of deforestation between two neighbouring countries can be significantly different (see contrasting past deforestation intensity for Haiti--Dominican Republic, Congo--DRC, French Guiana--Suriname, or Indonesia--Papua New Guinea for example). We assumed no contagious deforestation for the three study areas in India which are not connected (Fig. \@ref(fig:study-areas)).

The map of the relative spatial probability of deforestation in 2020 has a resolution of 30 m equivalent to an area of $r_{\text{ha}}=0.09$ ha. Using this map, we computed a probability threshold $p_y$ in the interval $[\![1, 65535]\!]$ identifying the $n_y$ forest pixels in 2020 with the highest probability of deforestation so that $n_y \times r_{\text{ha}} = D_y + \epsilon$. Because deforestation probabilities have finite values in the interval $[\![1, 65535]\!]$, some forest pixels might have the same deforestation probability and it might not be possible to identify $p_y$ such that $\epsilon=0$. We thus selected the threshold $p_y$ minimizing $\epsilon$. Because $D_y$ represents the total deforested area for several years and that few pixels had the same probability of deforestation, we always obtained negligible $\epsilon$ compared to $D_y$ ($\epsilon << D_y$). We considered those $n_y$ forest pixels in 2020 as deforested between years 2020 and $y$, and we derived the corresponding forest cover change map for the period 2020--$y$ (Fig. \@ref(fig:sm-proj)).

We projected the future forest cover for several years in the period 2030--2110 using a base time-interval of 10 years (Tables \@ref(tab:fcc-proj), \@ref(tab:fcc-proj-reg)). We also projected the future forest cover for years 2055 and 2085 as these two years are often used as pivot years in studies on future climate change. They correspond to 30-year climate averages on the periods 2040--2070 and 2070--2100, and to mid-term and long-term climate projections, respectively, for the 21^st^ century [@IPCC2014]. We then computed the percentage of forest cover loss in 2100 in comparison with the forest cover in 2000 for each study area and continent (Tables \@ref(tab:fcc-proj), \@ref(tab:fcc-proj-reg)). We also computed the year at which all the forest will have disappeared for each study area (Tables \@ref(tab:fcc-proj)). At the continental level, it makes less sense to compute the year at which all the forest will have disappeared, as some countries might conserve forest for a very long time, even though they account for a very small proportion of the total forest area at the continental scale. Instead, we computed the estimated year at which 75% of the forest cover in 2000 will have disappeared (Table \@ref(tab:fcc-proj-reg)).

We provided an estimate of the number of endemic species committed to extinction because of the complete loss of tropical forest by 2100 in 6 biodiversity hotspots (Mesoamerica, Guinean Forests of West Africa, Horn of Africa, Madagascar and Indian Ocean Islands, Indo-Burma, Western Ghats and Sri Lanka) as defined by @Mittermeier2011. To do so, we used estimates of the number of plant and vertebrate species endemic to each biodiversity hotspot (Table \@ref(tab:hotspots)). 

## Carbon emissions associated with deforestation

We estimated the carbon emissions associated with past deforestation (2010--2020) and projected deforestation (2030--2110) (Table \@ref(tab:c-em-sm)) using three recent global or pantropical maps providing estimates of aboveground dry biomass (AGB, in Mg/ha) on a date before 2010 (Fig. \@ref(fig:agb)). 

The first map by @Avitabile2016 from Wageningen University and Research (WUR) is a combination of two pantropical aboveground biomass maps by @Saatchi2011 and @Baccini2012. This map is representative of the aboveground biomass for the years 2000--2010 and provide AGB estimates at 1 km resolution. This fused map achieved a lower RMSE (87--98 Mg/ha representing a 5--74% decrease) and lower bias (a decrease of 90--153%) than the two input maps for all continents. This map was not covering some islands in the tropics: Mauritius, Reunion island, Fiji, New Caledonia, Solomon Islands, and Vanuatu. The second map by @Zarin2016 from the Woods Hole Research Center (WHRC) provides AGB estimates at a higher resolution of 30 m, at pantropical scale, for circa the year 2000. This map expands upon the methodology presented in @Baccini2012 using data from Landsat 7 ETM+ satellite imagery at 30 m resolution in place of MODIS data at 500 m resolution. The third map by @Santoro2021, obtained within the framework of the Climate Change Initiative of the European Space Agency (ESA CCI), provides AGB estimates at 100 m resolution at the global scale for the year 2010. For this third map, and contrary to the two previous maps based on passive optical sensors, AGB estimates were retrieved from active radar sensors (ALOS-PALSAR and Envisat-ASAR sensors) for which the signal is not sensitive to weather conditions (eg. clouds often present over tropical moist forests).

We used the Intergovernmental Panel on Climate Change (IPCC) default carbon fraction of 0.47 [@McGroddy2004] to convert aboveground dry biomass to carbon stocks. We assumed no change of the forest carbon stocks in the future while computing carbon emissions associated with projected deforestation. We estimated average annual carbon emissions for ten-year periods from 2010 to 2110. Under a "business-as-usual" scenario of deforestation (no change in the annual deforested area, in ha/yr, in the future), the change in mean annual carbon emissions in the future is only attributable to the spatial variation of the forest carbon stocks and to the location of the future deforestation. The three AGB maps were used separately to derive carbon emissions associated with deforestation and see if the changes in mean annual carbon emissions in the future were robust to change in the input data (Fig. \@ref(fig:ctrend)).

## Uncertainty analysis

An uncertainty surrounds the estimate of the mean annual deforested area $d$ (in ha/yr) for each study area. We took into account this uncertainty in our predictions (Data S1 and S2). We computed the 95% confidence interval of $d$ for each study area using the deforestation observations $d_t$ for the ten years $t$ from 2010 to 2020 (Table \@ref(tab:ci-d)). Deforestation observations $d_t$ were obtained from the forest cover change annual product by @Vancutsem2021. We estimated $d'$, the lower limit of the confidence interval ($d'=\bar{d_t}-1.96 \times \sigma(d_t)/\sqrt n$), and $d''$, the upper limit of the confidence interval ($d''=\bar{d_t}+1.96 \times \sigma(d_t)/\sqrt n$), with $\bar{d_t}$: the mean annual deforested area on 2010--2020 ($\bar{d_t}$=$d$), $\sigma(d_t)$: the standard deviation of the annual deforested area, and $n$: the number of observations ($n$=10, the number of years in our case). We repeated the simulations of the deforestation in the future using either $d'$ or $d''$ as the annual deforested area for each study area. We thus obtained three different predictions of the forest cover change and associated carbon emissions: an average prediction considering the mean annual deforested area $d$, a prediction considering a lower deforestation $d'$ (Fig. \@ref(fig:fcc2100-low)), and a prediction considering a higher deforestation $d''$ (Fig. \@ref(fig:fcc2100-high)). 

## Software used: the `forestatrisk` Python package

We developed a specific package called `forestatrisk` [@Vieilledent2021a] to model and forecast the tropical deforestation spatially using the Python programming language [@Python2020]. The package has an associated website at <https://ecology.ghislainv.fr/forestatrisk>. The package is installable either from GitHub at <https://github.com/ghislainv/forestatrisk> or PyPI (The Python Package Index) at <https://pypi.org/project/forestatrisk>. It can be easily installed using `pip` (the package installer for Python) in any Python virtual environment created with either `conda` (recommended) or `virtualenv`. The `forestatrisk` package includes functions (i) to build a dataset from deforestation observations (function `.sample`), (ii) to estimate the parameters of several spatial deforestation models (functions `.model*`, including function `.model_binomial_iCAR` for the "icar" model), (iii) to assess the model performance (function `.cross_validation`), (iv) to derive predictive maps of the probability of deforestation (functions `.predict_raster*`), and (v) to forecast future forest cover under a given intensity of deforestation (function `.deforest`). Using functions from the `forestatrisk` Python package makes computation fast and efficient (with low memory usage) by treating large raster data by blocks. Numerical computations on blocks of data are performed with the NumPy (<https://numpy.org>) Python package whose core is mostly made of optimized and compiled C code which runs fast [@Harris2020].

We also developed another smaller Python package called `pywdpa` (<https://ecology.ghislainv.fr/pywdpa>) that allows downloading the shapefiles of the protected areas for each country using the API of the World Database on Protected Areas (<https://api.protectedplanet.net>). The package is also available on GitHub at <https://github.com/ghislainv/pywdpa> or PyPI at <https://pypi.org/project/pywdpa>, and can also be easily installed using `pip`.

Computations for each country were run in parallel on the computing cluster of the Montpellier Bioinformatics Biodiversity (MBB) platform (<https://mbb.univ-montp2.fr>) provided by LabEx CeMEB (<http://www.labex-cemeb.org/>). Google Earth Engine [@Gorelick2017] was used to process the annual product by @Vancutsem2021 and derive the past forest cover change map for each country. While the raw results of our study (which implied intensive computations on large raster data) were obtained using the Python programming language, the summarized results (tables and figures) presented in this article (main text and supplementary materials) were obtained using the R software [@R2020].

<!-- ## Repeating the analysis with the tree cover loss product by @Hansen2013

We performed the exact same analysis replacing past forest cover change maps derived from the annual product of @Vancutsem2021 by forest cover change maps derived from the tree cover products of @Hansen2013. We assumed that the extent of the natural old-growth tropical moist forest cover in 2000 could be approximated by using a tree cover >70% at this date [@Vieilledent2018; @Aleman2017a]. Then, we used the tree cover loss provided by @Hansen2013 on the periods 2001--2009 and 2010--2019 to derive pantropical forest cover change maps on the periods 2000--2010--2020 at 30 m resolution. All the results we obtained were robust to the change of the past forest cover change map. Results obtained with the forest cover change maps derived from the tree cover products of @Hansen2013 are available on the CIRAD Dataverse repository (see below). -->

\nolinenumbers
\newpage
