#!/bin/bash -e
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -l h_rt=999:00:00
#$ -t 1-26 -tc 20
#$ -pe multithread8 3
#$ -N farBRA

# load singularity
module load singularity

# run python script inside container
singularity exec --bind /share/nas2-amap/gvieilledent ~/Code/forestatrisk-tropics/forestatrisk-tropics.simg python3 -u ~/Code/forestatrisk-tropics/Tropics/tropics-mbb-jrc-brazil.py $SGE_TASK_ID

# EOF
