\newpage

# Acknowledgements

Our warm thanks to Rémy Dernat and Philippe Verley for help using the computing cluster of the Montpellier Bioinformatics Biodiversity (MBB) platform. We are also grateful to all the members of the IFORCE group at the JRC in Ispra for their kind support during this work. **Funding**: BioSceneMada project funded by FRB-FFEM (AAP-SCEN-2013 I), Roadless Forest project funded by the European Commission, RELIQUES project funded by CNRT, LabEx CeMEB funded by ANR "Investissements d'avenir" programme (ANR-10-LABX-04-01). **Authors' contributions**: GV and FA conceived the study, CV provided the historical forest cover change maps and advice on using the deforestation annual product, GV performed the analysis and wrote the original draft, all authors reviewed and edited the final manuscript. **Competing interests**: All authors declare that they have no competing interests. **Data and materials availability**: All the data, code, and materials used for the analysis, and the resulting products of the study, can be found on the following website which accompanies the present publication: <https://forestatrisk.cirad.fr>. The code is also available on GitHub (<https://github.com/ghislainv/forestatrisk-tropics>) and has been permanently archived in the Cirad Dataverse repository (<https://doi.org/10.18167/DVN1/7N2BTU>).

# Supplementary Materials

Materials and Methods    
Figs. S1 to S14    
Tables S1 to S20    
Data S1 to S2    
References (49--78)

\nolinenumbers
\newpage