# Tables {-}

<!-------------------------------------------------->
<!-- Historical and projected forest cover change -->
<!-------------------------------------------------->

(ref:cap-fcc) **Past and predicted changes in forest cover**. We provide past and predicted forest cover for the three continents and for the three countries with the highest forest cover in 2010 for each continent (Brazil in America, the DRC in Africa, and Indonesia in Asia). Past forest cover areas (in thousand hectares, Kha) refers to their status on January 1^st^ 2000, 2010, and 2020 ("fc2000", "fc2010", and "fc2020", respectively). We provide the mean annual deforested area $d$ (Kha/yr) for the last ten-year period from January 1^st^ 2009 to January 1^st^ 2019 (deforestation in 2019 is not included, see Methods), and the corresponding mean annual deforestation rate $p$ (%/yr). Projected forest cover areas are given for the years 2050 and 2100 ("fc2050" and "fc2100"). Projections are based on the forest cover in 2020 ("fc2020") and the mean annual deforested area ($d$) assuming a business-as-usual scenario of deforestation. Column "loss21" indicates the projected percentage of forest cover loss during the 21^st^ century (2100 vs. 2000). We estimate the year ("yr75") at which 75% of the forest cover in 2000 will have disappeared.\vspace{0.5cm}

```{r fcc, results="asis", echo=FALSE}
## Import data
df1 <- read.table(here("Manuscript/Article/tables/fcc_hist_region_mean.csv"), header=TRUE, sep=",")
df2 <- read.table(here("Manuscript/Article/tables/fcc_proj_region_mean.csv"), header=TRUE, sep=",")
## Arrange data
df <- df1 %>%
  dplyr::select(area_cont, for2000, for2010, for2020, andef, pdef) %>%
  dplyr::bind_cols(df2) %>%
  dplyr::filter(area_cont!="India") %>%
  dplyr::select(area_cont, for2000, for2010, for2020, andef, pdef,
                for2050, for2100, loss21, yr75dis) %>%
  dplyr::mutate(andef=round(andef/1000), yr75dis=as.character(yr75dis),
                loss21=round(loss21)) %>%
  dplyr::mutate(id=c(2,3,1,4:7)) %>% arrange(id) %>% select(-id) %>%
  dplyr::mutate(area_cont=ifelse(area_cont=="All continents", "All cont.", area_cont)) %>%
  dplyr::mutate_at(.var=vars(starts_with("for")),.fun=function(x){round(x/1000)})
## Make table
vect.align <- c(rep("l", 1), rep("r", 9))
unit.vect <- c("", "(Kha)", "(Kha)", "(Kha)", "(Kha/yr)", "(\\%/yr)", "(Kha)", "(Kha)", "(\\%)", "")
col.names <- c("Regions", "fc2000", "fc2010", "fc2020", "$d$", "$p$",
               "fc2050", "fc2100", "loss21", "yr75")
knitr::kable(df, caption="(ref:cap-fcc)", booktabs=TRUE, longtable=FALSE,
						 format.args=list(big.mark=","),
						 escape=FALSE,
						 col.names=unit.vect,
						 align=vect.align, linesep="") %>%
  add_header_above(header=col.names, line=FALSE, escape=FALSE, align=vect.align) %>%
  pack_rows("Countries", 1, 3) %>%
  pack_rows("Continents", 4, 7) %>%
	kable_styling(latex_options=c("HOLD_position","striped","repeat_header"),
	              full_width=full_width_type,
	              bootstrap_options = c("striped", "hover"),
	              position="center", font_size=font_size_type, repeat_header_method="replace")
```

\newpage
