---
title: "`r params$title`"
author: "`r params$author`"
date: "`r params$date`"
fontsize: 12pt
output:
  bookdown::gitbook:
    number_sections: yes
    split_by: chapter  
    config:
      toc:
        collapse: section
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit: null
      download: ["pdf"]
      search: yes
      fontsettings:
        theme: white
        family: sans
        size: 2
      sharing:
        facebook: yes
        twitter: yes
        google: no
        linkedin: no
        weibo: no
        instapper: no
        vk: no
        all: ['facebook', 'google', 'twitter', 'linkedin', 'weibo', 'instapaper']
bibliography: /home/ghislain/Documents/Bibliography/biblio.bib
biblio-style: bib/Science.bst
#biblio-style: bib/jae.bst
link-citations: yes
csl: bib/science.csl
#csl: bib/journal-of-applied-ecology.csl
#always_allow_html: true
---

```{r options, include=FALSE, results="hide"}
library(bookdown)
library(knitr)
library(kableExtra)
library(here)
library(dplyr)
opts_chunk$set(echo=FALSE, cache=FALSE,
               # results="hide", 
               warning=FALSE,
               message=FALSE, highlight=TRUE,
               # fig.show="hide",
			         size="small",
               fig.align="center",
               fig.pos="H",
               tidy=FALSE)
#load("forestatrisk-tropics.rda")
```

\linenumbers

# Abstract {-}

Tropical forests are disappearing at an alarming rate due to human activities. Here, we provide spatial models of anthropogenic deforestation in 92 countries covering all the tropical moist forests in the world. We demonstrate the effectiveness of protected areas in displacing deforestation and the negative impact of roads on forest conservation in the tropics. We derive high-resolution pantropical maps of the deforestation risk and future forest cover for the 21^st^ century under a "business-as-usual" scenario. Although under this scenario, large areas of tropical moist forest should remain in the heart of the Amazon, in the Congo Basin, and in New Guinea in 2100, 61% of all forest cover is expected to disappear during the course of the 21^st^ century, and many countries will have lost all their forests by 2100. The remaining forests will be highly fragmented and located in remote places. As future deforestation will concern forests with higher carbon stocks, annual carbon emissions associated with tropical deforestation are expected to increase by +0.221 Pg/yr (+42%) during the 21^st^ century.

**Keywords:** deforestation, forecasts, forest cover change, forest refuge areas, moist tropical forests, spatial modelling, scenarios.

**One sentence summary:** Anthropogenic deforestation will affect tropical forests with higher carbon stocks in the future, thus increasing carbon dioxide emissions in the atmosphere.

\newpage
